MediaRecorder: audio encoder has already been set (MealAc录音：音频编码器已经被设置) 原因：开始录像的时候，已经了开启录音，抢用麦克风了。 解决方法：把setAudioSource(AudioSource.MIC);换成setAudioSource(AudioSource.DEFAULT)
java.io.IOException: No valid output file   (没有有效的输出文件)
mMediaRecorder.prepare();
检查文件地址是否创建